### ISSUE TITLE
error account/addresses/create

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#105]
![Captura de tela de 2020-11-19 12-12-07](https://user-images.githubusercontent.com/30912144/99684716-8914c980-2a60-11eb-916c-b3cf066361d7.png)

**Comment by bhanu-webkul** [comment]
please check with latest commit as there is no issue in customer registration and adding address

**Comment by marcelowu** [comment]
error client logged in and without address

**Comment by marcelowu** [comment]
error addresses/create,
client logged in address book,

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-26 13-33-27](https://user-images.githubusercontent.com/30912144/100376049-97795d00-2fed-11eb-93c5-d34db05c11c3.png)

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-26 13-32-35](https://user-images.githubusercontent.com/30912144/100376078-a52ee280-2fed-11eb-85a2-8c706c203b37.png)

**Comment by jyoti-webkul** [comment]
- Fixed

------------------------------
![Workspace 1_133](https://user-images.githubusercontent.com/45203177/100420067-c35b1800-30ab-11eb-9496-03605ba68090.png)
![Workspace 1_132](https://user-images.githubusercontent.com/45203177/100420071-c524db80-30ab-11eb-9701-984e5bea3aee.png)

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-27 20-18-23](https://user-images.githubusercontent.com/30912144/100488559-bc54f980-30ed-11eb-9dd6-a279f35828b2.png)
![Captura de tela de 2020-11-27 20-17-29](https://user-images.githubusercontent.com/30912144/100488566-c2e37100-30ed-11eb-9325-b1a9af15955a.png)
