### ISSUE TITLE
error applied coupon

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#106]
![Captura de tela de 2020-11-19 12-28-28](https://user-images.githubusercontent.com/30912144/99686844-c11d0c00-2a62-11eb-9ff3-2fd6d7d0fd63.png)

**Comment by shubhwebkul** [comment]
please share the screenshot of the exception you are facing.

**Comment by marcelowu** [comment]
![Captura de tela de 2020-11-20 10-28-26](https://user-images.githubusercontent.com/30912144/99805348-26343880-2b1b-11eb-97b9-0054054fd7a2.png)
