### ISSUE TITLE
how to add language

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#107]
![Captura de tela de 2020-11-19 12-31-24](https://user-images.githubusercontent.com/30912144/99687226-2a048400-2a63-11eb-83c8-7fe0422b959d.png)

**Comment by bhanu-webkul** [comment]
you can add multiple locale from admin pannel- settings>locale

**Comment by marcelowu** [comment]
done, but it doesn't work in PWA.
is work in velocity theme

![Captura de tela de 2020-11-19 13-16-39](https://user-images.githubusercontent.com/30912144/99692904-908ca080-2a69-11eb-926e-63153a90987d.png)
![Captura de tela de 2020-11-19 13-16-08](https://user-images.githubusercontent.com/30912144/99692910-91bdcd80-2a69-11eb-8c72-4750e5b60bf5.png)

**Comment by marcelowu** [comment]
need install package.json?
npm run production

**Comment by shubhwebkul** [comment]
![Screenshot from 2020-11-19 22-31-52](https://user-images.githubusercontent.com/41280839/99698741-239ff780-2ab7-11eb-82c9-9a6f28014916.png)

**Comment by shubhwebkul** [comment]
You can click on language option on the sidebar to get languages

**Comment by marcelowu** [comment]
yes, always english

![Captura de tela de 2020-11-19 14-32-52](https://user-images.githubusercontent.com/30912144/99702236-4eb52780-2a74-11eb-8ff2-bb4d307bfc4f.png)

**Comment by marcelowu** [comment]
have to create or translate that file?

src/Resources/assets/js/lang/en.json

**Comment by marcelowu** [comment]
I've tried everything, and nothing,
I need to create a file ?  vendor/bagisto/pwa/src/Resources/assets/js/lang/pt_BR.json

**Comment by shubhwebkul** [comment]
Indeed! currently we are using en.json only, you need to translate file in whatever language you want.

That will be great if you will contribute in this repository.

**Comment by marcelowu** [comment]
after translating, which next step works, here it didn't work

**Comment by marcelowu** [comment]
is ok, 
sudo yarn development
 
![Captura de tela de 2020-11-24 14-10-16](https://user-images.githubusercontent.com/30912144/100128396-f9f02300-2e5e-11eb-9b01-5668b7258f90.png)


![Captura de tela de 2020-11-24 14-07-04](https://user-images.githubusercontent.com/30912144/100127987-72a2af80-2e5e-11eb-8537-e4e9ee4edb66.png)
