### ISSUE TITLE
paypal undefined

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#108]
![Captura de tela de 2020-11-19 12-34-08](https://user-images.githubusercontent.com/30912144/99687639-a7c88f80-2a63-11eb-9a08-27637d10c43e.png)

**Comment by shubhwebkul** [comment]
Hello there,
Is it working when you try to make payment via website ?

**Comment by marcelowu** [comment]
not

**Comment by shubhwebkul** [comment]
please raise issue here:- http://github.com/bagisto/bagisto/issues
