### ISSUE TITLE
add a home button

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#109]
unsuccessful payment, back to the store page, but, direct to the paypal page,

![Captura de tela de 2020-11-19 12-41-06](https://user-images.githubusercontent.com/30912144/99688727-e448bb00-2a64-11eb-9a18-ffc8a33dc373.png)
![Captura de tela de 2020-11-19 12-40-46](https://user-images.githubusercontent.com/30912144/99688733-e579e800-2a64-11eb-8043-b778f5bd3187.png)

**Comment by jyoti-webkul** [comment]
- Added

----------------------
![Workspace 1_147](https://user-images.githubusercontent.com/45203177/100710299-848fcf80-33d5-11eb-8474-a0d0e870b7e5.png)
