### ISSUE TITLE
default_country does not work

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#110]
![Captura de tela de 2020-11-19 12-47-40](https://user-images.githubusercontent.com/30912144/99689318-9d0efa00-2a65-11eb-9c4a-c4f1bf5d1060.png)
![Captura de tela de 2020-11-19 12-39-09](https://user-images.githubusercontent.com/30912144/99689323-9da79080-2a65-11eb-8da7-0c49901c853b.png)

**Comment by bhanu-webkul** [comment]
could you please mention steps to reproduce issue

**Comment by marcelowu** [comment]
set up here config/app.php

**Comment by shubhwebkul** [comment]
We only provide default currency not default country
