### ISSUE TITLE
layout issue on sign and registration page

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-pwa#111]
![Screenshot from 2020-11-19 21-21-10](https://user-images.githubusercontent.com/52821836/99689800-6d83e000-2aad-11eb-800a-421f3e4397ec.png)
create an account twice

![Screenshot from 2020-11-19 21-23-52](https://user-images.githubusercontent.com/52821836/99689904-8a201800-2aad-11eb-8b4c-7d9d8d9b1253.png)
signin or registration in middle

**Comment by bhanu-webkul** [comment]
not fixed on forgot password field 
![Screenshot from 2020-11-20 10-15-57](https://user-images.githubusercontent.com/52821836/99760348-86c27600-2b19-11eb-9e49-05e5f51bbbb3.png)

**Comment by bhanu-webkul** [comment]
https://prnt.sc/vmwffh

**Comment by jyoti-webkul** [comment]
- Fixed

------------

![Workspace 1_121](https://user-images.githubusercontent.com/45203177/100367533-5c484f80-3028-11eb-8d56-53b8206cf207.png)
