### ISSUE TITLE
error save-order

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#112]
![Captura de tela de 2020-11-19 13-12-19](https://user-images.githubusercontent.com/30912144/99692329-f6c4f380-2a68-11eb-9f81-9bbf343737de.png)

**Comment by shubhwebkul** [comment]
please mention steps to reproduce because we are not facing such kind of issue

**Comment by marcelowu** [comment]
https://github.com/cagartner/bagisto-pagseguro
may be the payment plugins

![Captura de tela de 2020-11-19 14-51-02](https://user-images.githubusercontent.com/30912144/99704142-bc625300-2a76-11eb-8caa-2d8606237bf2.png)

**Comment by shubhwebkul** [comment]
This is bagisto core issue not related to PWA extension, if you are facing this issue.

Kindly raise it here
http://github.com/bagisto/bagisto/issues

**Comment by marcelowu** [comment]
> Este é o problema principal do bagisto não relacionado à extensão PWA, se você estiver enfrentando esse problema.
> 
> Por favor, aumente aqui
> [http://github.com/bagisto/bagisto/issues](https://github.com/bagisto/bagisto/issues)

removed pwa, is works my plugins
