### ISSUE TITLE
customer is unable to send forgot password link on registered mail 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-pwa#114]
as getting 500 error 

![Screenshot from 2020-11-20 10-16-20](https://user-images.githubusercontent.com/52821836/99760454-c4bf9a00-2b19-11eb-95ff-29bccb4faf24.png)

**Comment by shubhwebkul** [comment]
please check you SMTP configuration

**Comment by bhanu-webkul** [comment]
working fine
