### ISSUE TITLE
error create an account

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#121]
![Captura de tela de 2020-11-24 11-37-40](https://user-images.githubusercontent.com/30912144/100108515-9e676a80-2e49-11eb-9c9d-fa0c9c71991d.png)
![Captura de tela de 2020-11-24 11-36-39](https://user-images.githubusercontent.com/30912144/100108524-9f989780-2e49-11eb-9532-ef9f084e0166.png)

**Comment by jyoti-webkul** [comment]
Working fine now

**Comment by marcelowu** [comment]
yes
