### ISSUE TITLE
Please update pwa for bagisto latest version

### ISSUE THREAD

**Issue by Kuntal1230** [bagisto/laravel-pwa#13]
its not working on latest version of bagisto. please update it for latest version.

**Comment by marcelowu** [comment]
not even in the version is working 0.2.2
![2020-05-08 23-56-30屏幕截图](https://user-images.githubusercontent.com/30912144/81475213-2f922f00-91e1-11ea-8206-de4df707b116.png)
![2020-05-09 04-08-46屏幕截图](https://user-images.githubusercontent.com/30912144/81475231-49cc0d00-91e1-11ea-888a-a544d1245ee2.png)
