### ISSUE TITLE
how configures brazil for default country

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#131]
![Captura de tela de 2020-11-27 20-27-09](https://user-images.githubusercontent.com/30912144/100488860-75680380-30ef-11eb-907e-c0a5c9e8a1e1.png)

**Comment by shubhwebkul** [comment]
there is no such feature for default country, you can customize [component](https://github.com/bagisto/laravel-pwa/blob/master/src/Resources/assets/js/components/checkout/onepage/index.vue#L400) for that
