### ISSUE TITLE
Not able to make Home Page Content field blank for PWA after entering some content in it

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#166]
Bagisto: 1.2.0
PWA: Master

Expected Result: It should become blank if user want to leave it blank

https://user-images.githubusercontent.com/53482391/108060613-1aee9b80-707d-11eb-9da3-035ce692ccc5.mp4

**Comment by Nikitajoshi39** [comment]
**Fixed:**
![pwa14](https://user-images.githubusercontent.com/92033944/162183640-327edcf7-6457-4895-8a8c-4fbfd8696c28.png)
