### ISSUE TITLE
Push Notification isn't working even on secured server. Not enough field for entering all Firebase credentials

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#167]
Bagisto: 1.2.0
Branch: Master

1. Firebase Service Worker isn't getting registered.
2. These columns are are required for entering all credentials.

**Expected**

![pp](https://user-images.githubusercontent.com/53482391/108062209-7883e780-707f-11eb-91eb-c70128185771.png)

**Actual**

![pwapwapwa](https://user-images.githubusercontent.com/53482391/108062425-c7ca1800-707f-11eb-9b32-a83e26a51030.png)

3. Video

https://user-images.githubusercontent.com/53482391/108062289-994c3d00-707f-11eb-8c89-8230e2c22be0.mp4

**Comment by Nikitajoshi39** [comment]
duplicate issue :https://github.com/bagisto/laravel-pwa/issues/244
