### ISSUE TITLE
There isn't any compare product option which is a feature of Bagisto 1.2.0

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#175]
Implement compare product option in PWA.

**Comment by ashishkumar-webkul** [comment]
**Bagisto V1.3.3**

Checked and Found that the compare product has been added to the Module. Attaching the video for the future reference. Hence closing the issue.

**Video**

https://user-images.githubusercontent.com/92721837/147730944-4110ce54-e1fb-4d4a-8405-f62a62789a87.mp4
