### ISSUE TITLE
Quantity Issue in cart

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#179]
If you add a product in cart with quantity of 5.
And Now Admin change the product quantity from 5 to 3.
Now go to cart and click on proceed to checkout. (It will proceed to checkout on Address and then it throws 500 internal  error.

What should happen ?
It should show a message that (the current quantity is not available at the moment) like it shows when we update the cart.

**Comment by Nikitajoshi39** [comment]
**Fixed:**

![pwa13](https://user-images.githubusercontent.com/92033944/162183080-1b2ff7e4-24b5-4fde-9e47-83b89498a1a6.png)
