### ISSUE TITLE
Error in Paypal smart button

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#193]
When using PWA it shows different  error for wrong credentials and for front end it shows different.

PWA: https://tinyurl.com/y7up3h2x

Velocity:
![Screenshot 2021-03-03 17:34:46](https://user-images.githubusercontent.com/53482391/109803632-4c539380-7c47-11eb-8998-1c7c740ccfc6.png)

**Comment by vishal-webkul** [comment]
@aayushbhatt18 kindly use valid credentials because it is working fine at my instance

**Comment by aayushbhatt18** [comment]
That can be done but while showing the error message, The error message must be same in both i.e PWA and front end.

**Comment by vishal-webkul** [comment]
@aayushbhatt18 I have checked at my instance PWA shows same errors as it is displaying on front end.

**Comment by naresh-webkul** [comment]
working fine:
https://prnt.sc/h6ABR_iz971A
