### ISSUE TITLE
Enhancement - payment and shipping description should be visible on the checkout page, like default bagisto

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#194]

**Comment by aayushbhatt18** [comment]
Still same on 1.3.0

**Comment by naresh-webkul** [comment]
FIxed:
https://prnt.sc/sdJEHr_Em-oq

**Comment by Nikitajoshi39** [comment]
**Fixed:**

![pwa11](https://user-images.githubusercontent.com/92033944/162178804-780f0985-66ea-4b4a-b64d-df1513200239.png)
