### ISSUE TITLE
UI issue at bundled product page

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#195]
https://tinyurl.com/yceqwfrm

**Comment by vishal-webkul** [comment]
@aayushbhatt18 No UI issue found in PWA it is same as it is shown on front end
https://prnt.sc/10zpd0x
https://prnt.sc/10zpdim

**Comment by musawirjon** [comment]
@vishal-webkul Please look into the issue https://github.com/bagisto/laravel-pwa/issues/198 as well.
