### ISSUE TITLE
PWA current version has some compitability issues

### ISSUE THREAD

**Issue by musawirjon** [bagisto/laravel-pwa#198]
Hello friends their are several issues which are not resolved in updated version.
I have the latest bagisto and pwa installed. But I am facing several issues and the code in the latest repo doesn't resemble with baigsto.
Please have a look into it and if possible then please resolve those basic issues.
=> 1: category filterable attributes are returning function not defined issue. And I can't find that method in bagisto as well

- Controller path (laravel-pwa/src/Http/Controllers/Shop/API/APIController.php). You can see the issue on pwa while navigating to the category page.
- Screenshot below:
  
![Screenshot from 2021-06-14 13-41-04](https://user-images.githubusercontent.com/18184776/121864858-c7344c00-cd16-11eb-8be9-33852e124b94.png)

=> 2: PWA not showing add to the home screen option in this new version.( Note: I cleared the cache of browser I did every possible solution but no luck)

=> 3: PWA is way slow, it should a bit faster. As on first go to every category, it shows nothing found, but after loading and loading it shows then products in the respective category.
@vishal-webkul @ghermans @rahulcs0082 @shubhwebkul

**Comment by ghermans** [comment]
Hi @musawirjon we are aware that there are currently compatibility issues , due the fact that we are currently working with a minimum of people on the open source projects (bagisto and its free modules, such as PWA..) we cannot make all plugins compatible at the same time, that being said, we will update this module as soon as possible.

**Comment by musawirjon** [comment]
Hello, @ghermans it's the method removed from bagisto new version. Other than that all is working fine. But this one is a major issue, and the developers can simply put back that removed method.
I can't figure the DB structures, I tried on my own to fix it. but didn't figure out the flow.

**Comment by ashishkumar-webkul** [comment]
Checked the PWA, and it is working in Version V1.3.3.
