### ISSUE TITLE
Translation Issue 

### ISSUE THREAD

**Issue by aayushbhatt18** [bagisto/laravel-pwa#204]
Even after changing locale in PWA, it always show English.

Steps to reproduce:
1. Add 2-3 locales to your channel from backend.
2. Try to change locale from PWA front.

Expected: PWA front should be translated into specific loacle.
Actual: It only shows English.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the concern is still being faced. Only English Language is working Even we have selected other language as the default language.

Check the video for the reference.

https://user-images.githubusercontent.com/92721837/147730290-17bf0a15-88be-4aa5-ac25-f650888f6688.mp4

**Comment by naresh-webkul** [comment]
not getting this issue
