### ISSUE TITLE
Wishlist Icon is not visible at the Category in PWA - V1.3.3

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#207]
**Bagisto Version - v1.3.3**
**PWA Version - v1.3.3**

**Description**
When checking the flow and functionality of the module at the PWA mobile view there, when we select the category and when we look at the products we are unable to see the wishlist icon when we are login. 
We can see the icon when we will click the product.

**How to Reproduce**

**1.** Go to Velocity Page -> Login with customer -> Category -> Products -> Check the icon, it is visible here.

**2.**  Now open the PWA page -> Category -> Product -> Unable to see the wishlist icon.

**Actual Result**
 
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**

https://user-images.githubusercontent.com/92721837/146912303-1d461aa6-d385-4f3c-9d3c-1827f41f14d7.mp4

**Expected Result**

The wishlist icon must appear as similar as the velocity page. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
Fixed:
https://prnt.sc/friwBNAFSork

**Comment by Nikitajoshi39** [comment]
Fixed:
![pwa](https://user-images.githubusercontent.com/92033944/162148729-d3f24ce7-e569-47a6-96c7-493435cdab15.png)
