### ISSUE TITLE
In Bundle product Actual Price is not cancelled when applied with the Special Price.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#208]
**Bagisto Version - v1.3.3**
**PWA Version - v1.3.3**

**Description**
When checking the flow and functionality of the module at the PWA mobile view there, when we see that the bundle product price is having a special price but there the actual price is not canceled.

**How to Reproduce**

**1.** Go to Velocity Page -> Login with customer -> Bundle Product -> Check the price, it is visible here.
**2.**  Now open the PWA page ->  Bundle Product -> Both the prices are visible.
**3.** Here the actual price is not canceled. The special price must be clear.

**Actual Result**
 
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**

https://user-images.githubusercontent.com/92721837/146914612-9df260ed-9898-43ce-a7cb-0e320d3b66eb.mp4

**Expected Result**

The Special Price must be visible and the Actual price must be canceled. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
Fixed :
https://prnt.sc/RDQ58ufSIXns

**Comment by Nikitajoshi39** [comment]
**fixed:**

![pwa15](https://user-images.githubusercontent.com/92033944/162190373-fba4da1f-69a8-4a77-83fd-1ade5335d709.png)
