### ISSUE TITLE
Space Required in the Special Price and Actual Price in Bundle Product and also in simple product

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#209]
**Bagisto Version - 1.3.3**
**Description**

When checking the details it was found that there is no space between the bundle product price. The special price and actual price is in continuation.

**How to Reproduce**

**1.**  Go to Velocity -> Login with customer -> see the price of the bundle product.

**2.**  Now check the same concern in PWD, there we will be able to see no gap.

**Actual Result**
 
 Check out the video and screenshots for a better understanding of the concern.
 
 **Velocity Theme Screenshot**
 
![Gap in Price](https://user-images.githubusercontent.com/92721837/146921359-75e4646d-5f75-4243-8f4b-b34fe2c1ccc8.png)

**PWD Mobile View** 
 
![Gap Required](https://user-images.githubusercontent.com/92721837/146921432-51d627f9-15af-4cb9-b372-2b50cbcaa7af.png)

![No Gap ](https://user-images.githubusercontent.com/92721837/146921452-e6487891-9f05-4bb5-9440-4811ac80c846.png)

![Screenshot from 2021-12-21 17-43-14](https://user-images.githubusercontent.com/92721837/146928421-0e2510ce-580f-4cae-ac80-5ca3a89a1a0b.png)

**Expected Result**

There must be some space in between which must be good for the appearance. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
Fixed :
https://prnt.sc/RDQ58ufSIXns
