### ISSUE TITLE
Unable to Add Product in the Compare list from Category.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#210]
**Bagisto Version - V1.3.3**
**PWD Version - V1.3.3**

**Description**
When we add the product from the front page to compare list we are to do so, but when we add the product from the category we are unable to do so.
From both ends, it must work properly.
 
**How to Reproduce**

**1.** Go to PWD mobile view -> Add the product to compare list from front page -> we are able to do so.

**2.** Now do the same from the Category, we are unable to do it.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 **Video**
 
https://user-images.githubusercontent.com/92721837/146922679-5adb46b4-1c32-4749-a340-fba60944c16c.mp4

**Expected Result**

From both area, this must work properly. Please Fix the issue regarding this concern.

**Comment by Nikitajoshi39** [comment]
**Fixed:**


https://user-images.githubusercontent.com/92033944/162177297-7878d69e-f6a8-4ab4-8f1f-b2fa4f4c04a0.mp4
