### ISSUE TITLE
UI Issue -  Booking Product appointment product location area.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#212]
**Bagisto Version - V1.3.3**
**PWA Version - V1.3.3**

**Description**
While checking the appointment product there we can see that the location is having some UI issues that should be properly aligned. 

**How to Reproduce**

**1.**  Go to PWA mobile view -> Login with Customer -> Check the Booking Product -> Location

**2.**  There we will be able to see this UI issue.

**Actual Result**
 Check out the screenshot for a better understanding of the concern.
 
 **Screenshot**
 
![UI issue](https://user-images.githubusercontent.com/92721837/146926770-a008cebb-45e3-4d10-aef4-2d963609c91e.png)

**Expected Result**
Shift the view on the map on the corner for a better appearance in the UI. Please Fix the issue regarding this concern.

**Comment by Nikitajoshi39** [comment]
Fixed
