### ISSUE TITLE
UI Issue -  At the Cart, Update Card and Empty Cart improper alignment.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#213]
**Bagisto Version - 1.3.3**
**Description**
When adding the product was to the cart it was observed that the Update Cart and Empty Cart is having improper alignment that needed to be corrected.

**How to Reproduce**
**1.** Go to PWA mobile view -> Add the products to the cart -> Visit the cart -> We will be able to see the concern.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 **Video**

https://user-images.githubusercontent.com/92721837/146929510-fbb958d4-3d4d-4a49-8061-3f825ef44f84.mp4

**Expected Result**
The alignment should be perfect, they must be in right and left corners. Please Fix the issue regarding this concern.

**Comment by Nikitajoshi39** [comment]
**Fixed:**

![pwa10](https://user-images.githubusercontent.com/92033944/162177903-0dcab681-d4d5-4327-b425-de162ce344d7.png)
