### ISSUE TITLE
Name in Bundle Product are cutting and also add a bit dark blue colour at drop-down for more visibility of the Name.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#214]
**Bagisto Version - V1.3.3**
**PWA Version - V1.3.3**
**Description**
When looking at the bundle product there I checked and found that the Product name is cutting and at the dropdown, the color is a bit light due to which the Name is not visible clearly.

**How to Reproduce**
**1.**  Go to PWA mobile view -> Bundle Product ->  Check the details 
**2.**There we will be able to see the concern. 

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
 
https://user-images.githubusercontent.com/92721837/146933330-c9518247-2574-42b1-b922-194460e8ccb4.mp4

**Expected Result**
1.  The Product Names must be clearly visible as they must not be cut.
2. **Suggestion - Use a bit of Dark Blue color so that the Name will be clearly visible at dropdown**
Please Fix the issue regarding these concerns.

**Comment by naresh-webkul** [comment]
working fine
https://prnt.sc/YBMYS5JAA1WQ
