### ISSUE TITLE
PWA Background must not scroll while viewing in mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#215]
**Bagisto Version - V1.3.3**
**PWA Version -V1.3.3**
**Description**

When checking the flow of the pwa in mobile view I found that the background is scrolling in mobile view. This must not happen in the case of mobile but in the Tablet view, it's ok. 
Mobile has a small screen and hence background must not scroll only main features clicked from the three-line must scroll.

**How to Reproduce**

**1.**   Go to PWA mobile view -> click on Three-lines -> Scroll the features and then scroll in the background.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.

 **Video**

https://user-images.githubusercontent.com/92721837/147076596-8cd4ec71-7808-461f-9a45-e3f019307bac.mp4

**Expected Result**
**Suggestion - It would be better if the Background is not scrolling if the main features are checked from the three lines.**

**Comment by naresh-webkul** [comment]
Invalid issue
