### ISSUE TITLE
PWA Mobile View - Recent Orders - Search Bar, Instead of Search Bar Filters must be there.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#216]
**Bagisto Version - V1.3.3**
**Description**
When checking the details of the recent order on PWA mobile view it was found that the Search option is there with the details of the filters like Order ID, Date, Price, etc.

**How to Reproduce**

**1.** Go to PWA mobile view -> Login with customer  -> Dashboard -> Recent Orders

**2.** There at the top we will be able to see the Search bar.

**3.**  Also it was found that the search bar is not working properly. Unable to search for the desired result.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147538475-a6756546-20ff-43e6-9c84-8b9aa2cc07f1.mp4

**Expected Result**
Instead of having the search bar, it would be much better that there must be Filters with the details about what to search.
Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
search bar is working fine

**Comment by Nikitajoshi39** [comment]
**Working fine**

![pwa12](https://user-images.githubusercontent.com/92033944/162181539-09e558e2-e0a3-4b65-ba19-c400dc55591f.png)
