### ISSUE TITLE
Unable to Place Order of Downloadable Products. Product is in Stock, Requested Qty is not available.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#217]
**Bagisto Version - V1.3.3**

**Description**
When trying to buy the downloadable product and after adding it to the cart and processing the payment there I was unable to process the payment and also it is delivering the message Requested Qty is not available, Even the qty is there.
Tried the same concern in the Velocity theme, and there it is working fine.

**How to Reproduce**
**1.** PWA mobile view -> Add the downloadable product to the cart -> Process for buying -> Unable to place the order.
**2.** Unable to do the payment and shipping after selecting the address.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 **Video**

https://user-images.githubusercontent.com/92721837/147540209-eed8a548-8bed-459a-987d-a78c5ecbf9c0.mp4

**Expected Result**
Downloadable Products must also be processed for payment and also this must complete the buying process as similar to the velocity.
Please Fix the issue regarding this concern.

**Comment by ashishkumar-webkul** [comment]
New issue also occurred in this, now if we process for the buying the product, we are logged out and directed to the login page.

**Check the video -** 

https://user-images.githubusercontent.com/92721837/147659157-d7bde0d1-a77d-44d4-b2a9-a0ac91dffed2.mp4

**Comment by Nikitajoshi39** [comment]
**fixed**
