### ISSUE TITLE
Wish-list icon issue ->Wish-list add to cart button UI issue.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#218]
**Bagisto Version - V1.3.3**
**Description**
**1.** When adding the product to the wishlist there the wishlist icon becomes black, when checking the wishlist there the product is visible, but when we move back to the page the wishlist icon becomes white. 
**2.**  When checking the wishlist it was observed that Add to Cart icon is having UI issue.

**How to Reproduce**
**1.** Add the product to the wishlist and check the icon color -> Now see the product in the cart -> Now check the product in the front screen -> Icon becomes white.
**2.**  There in the wishlist page, Add to cart is also having UI issues.

**Actual Result** 
 Check out the video and screenshots for a better understanding of the concern. 
 **Video**

https://user-images.githubusercontent.com/92721837/147543742-e1829647-369d-4ae1-ae8b-396f3915858d.mp4

**Expected Result**
**1.**  The add-to-cart icon must be of similar size which looks good in UI.
**2.**  The wishlist icon must be black if the product is added to the wishlist, so that no confusion occurs, which product is added or not.
Please Fix the issue regarding this concern.

**Comment by Nikitajoshi39** [comment]
**Fixed:**

![pwa6](https://user-images.githubusercontent.com/92033944/162169993-907facff-05d1-4324-974e-9d98859291b4.png)
