### ISSUE TITLE
UI Issue is occurring at the front end after creating all the products in the front end of PWA mobile view. Especially in Bundle and Group Product Price

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#219]
**Bagisto Version - V1.3.3**
**Description**
When adding all the products and checking the front end of the PWA mobile view it was found that the UI in price amount is merging with other product price.

**How to Reproduce**
**1.** Add all the products from admin -> Check the product in the PWA mobile view.
**2.** In the front end we will be able to see the UI issue.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147654131-4935e2b1-e227-4f06-817b-636aefde0690.mp4

**Expected Result**
The prices must be clear in the front end and they must not merge with other product price.
Please Fix the issue regarding this concern.

**Comment by Nikitajoshi39** [comment]
**Fixed:**

![pwa17](https://user-images.githubusercontent.com/92033944/162193186-205d050d-8ce4-4654-9a1c-cdbda3f95055.png)
