### ISSUE TITLE
Logging in to store after installing PWA

### ISSUE THREAD

**Issue by mhd-yasser-haddad** [bagisto/laravel-pwa#22]
Versions
PHP version: 7.2.0
Laravel version: 6.18.1

I installed the PWA package to my bagisto project, but after I installed I tried to login to the store and got this error:
![1](https://user-images.githubusercontent.com/44609144/84041652-c1da4e00-a9ac-11ea-9938-64f3dc4d1b73.JPG)
I fixed this error by replacing the public function `saveCustomerAddress($data)` and adding `public function saveCustomerAddress($data): bool` in "packages/Webkul/PWA/src/cart.php"

After I fixed this error I ran into a new error which was this:
![2](https://user-images.githubusercontent.com/44609144/84045028-fcde8080-a9b0-11ea-961d-7dc3fb68a3d7.JPG)
I looked it up and found this link which helped fix the error:
[https://forums.bagisto.com/topic/1100/class-webkul-product-helpers-price-does-not-exist/3](https://forums.bagisto.com/topic/1100/class-webkul-product-helpers-price-does-not-exist/3)
I added a new file in the helpers folder in product package "packages/Webkul/Product/src/Helpers"

After I fixed this issue, I got a new one which was this:
![3](https://user-images.githubusercontent.com/44609144/84046163-6612c380-a9b2-11ea-8b7e-b416b9b8666d.JPG)
I looked it up, but I was unable to find a fix for it, could you please help me?
Thanks in advance

**Comment by marcelowu** [comment]
bagisto 0.2.2

**Comment by mhd-yasser-haddad** [comment]
After looking more deeply into the code, all I had to do was to go to the cart.php file in the directory "packages/Webkul/PWA/src/Cart.php" and remove the customer variable from the parent construct in line 121 since it was removed from the parameters in the construct.
![11111](https://user-images.githubusercontent.com/44609144/84568560-eb1e2400-ad88-11ea-9224-785f0aa4b9fd.JPG)
That's all
