### ISSUE TITLE
In Configuration Product, all variant images are coming same even saved with different images.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#221]
**Bagisto Version - V1.3.3**
**Description**
When adding the Configurable product in the cart and there it was found that the images of the Config products all are coming same. This must not happen.

**How to Reproduce**
**1.** Go to  PWA mobile view -> Add the config  product -> check the images
**2.** There we will be able to see that the images are all same.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147658671-ea1aebee-01fd-4cc7-a86f-33899d7693ae.mp4

**Expected Result**
Images must occur as per the selected product. Please Fix the issue regarding this concern.

**Comment by Nikitajoshi39** [comment]
**Fixed:**


https://user-images.githubusercontent.com/92033944/162192543-743e4288-dd6f-4fe2-b863-14ff205dac84.mp4
