### ISSUE TITLE
Functionality of Category at search bar not working  in PWA mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#222]
**Bagisto Version - V1.3.3**
**Description**
When searching the product and there when we select the category, the functionality of the product is not working. 

**How to Reproduce**
**1.** Go to  PWA mobile view -> Search bar -> Category -> Click on them -> No Response.
**2.** They must direct to the category page.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147659547-7d5a195f-d8dd-4366-a051-ca0b05c7f9e6.mp4

**Expected Result**
Functionality must work accordingly the selected category. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
@Nikitajoshi39 
These are only listing of the categories. 
We will add the category page link on them in upcoming updates.

**Comment by Nikitajoshi39** [comment]
**Fixed**
