### ISSUE TITLE
Configure Product Varients are not visible individually in PWA mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#223]
**Bagisto Version - V1.3.3**
**Description**
In admin panel we have already edited the variant for visible individually, but still in the front end, they are not visible. Like in the velocity page if we select variant for visible individually they appear at the front page.

**How to Reproduce**
**1.**  Go to Admin -> Edit  the Config. Variant -> Visible individually -> PWA mobile view -> Check there.
**2.** Here we are unable to see the product 
 
**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147660939-f985a45a-6c5e-41dc-95b0-372b96cec54f.mp4

**Expected Result**
Config Variant Products must also be visible at the front. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
Fixed:
https://prnt.sc/S6YZ0MMCvz4d

**Comment by Nikitajoshi39** [comment]
**Fixed:**
