### ISSUE TITLE
No items are visible at the Compare list even products are added to the compare list.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#225]
**Bagisto Version - V1.3.3**
**Description**
When we add  the product to the compare list in the PWA mobile view and then we check the product in the compare list we are unable to see the product. It is empty. This must not occur.

**How to Reproduce**
**1.** Add the product in compare list -> Check the product in the compare list -> We are unable to see the product over there.
**2.** Message occurs - Product added to the compare list - Product already added to the compare list.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147663126-6866ece1-e872-40df-b501-7749dbbed23a.mp4

**Expected Result**
Compare products must be visible. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
Not getting this issue

**Comment by Nikitajoshi39** [comment]
Items are visible in the Compare list.

![PWA1](https://user-images.githubusercontent.com/92033944/162154065-06b6766f-b170-4a3b-b6bc-600a79c43377.png)
