### ISSUE TITLE
PWA Mobile View Category Logo is not same which we have saved.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#226]
**Bagisto Version - V1.3.3**
**Description**
When we feed the details of the Category and set the Image and Logo we observe that the Image is visible at the logo area in PWA mobile view category.

**How to Reproduce**
**1.** Go to Admin - Create Category -> Insert Different Image of the logo and Image -> Save the details.
**2.** Now check the details at the PWA mobile view we will observe that the images are same. Logo image is not visible.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147666000-80004608-4933-4f47-98c5-fb996783100f.mp4

**Expected Result**
The Logo image must appear at the logo place and when clicking  in the category then we cam see the image. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
Invalid issue :
because Category image is showing at the PWA category front and it is right. category logo will not display here
