### ISSUE TITLE
Sale icon is not visible in the PWA mobile view.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#227]
**Bagisto Version - V1.3.3**
**Description**
When we apply any special price to the product then the sale icon must be present there. So that the customer can get to know directly.

**How to Reproduce**
**1.** Apply Special Price to any product -> Check the Sale detail in the PWA mobile view.
**2.** We are unable to see the sale icon, In Velocity theme it is present.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**
https://user-images.githubusercontent.com/92721837/147721642-e71ba3c6-6717-40a4-a2ff-21d344ed8e08.mp4

**Expected Result**
The sale icon must be visible for the products with special price. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
invalid issue as both regular and special price are already showing at the shop. so user can easily know the product is in the sale
