### ISSUE TITLE
Change Current Password, New Password Option is missing in Edit Profile in PWA mobile View.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#228]
**Bagisto Version - V1.3.3**
**Description**
When editing  the profile of the customer in the PWA mobile view it was found that the Password area some Grids are missing.
Like Change Current Passsword, New Password.
**How to Reproduce**
**1.** Go to to PWA mobile view -> Customer Profile Edit -> Password Grid.
**2.** Please check the concern related to this as this must be similar to Mobile View.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 **Video**

https://user-images.githubusercontent.com/92721837/147727780-b38481cf-7e2f-4a89-8881-7c14e8a71b23.mp4

**Expected Result**
All the options related to the password must be present at the PWA mobile view customer edit section. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
core api issue now fixed in legacy api
https://github.com/bagisto/legacy-api/blob/master/src/Http/Controllers/Shop/SessionController.php#L111
