### ISSUE TITLE
Change Mobile Number grid is not visible in the profile edit section.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/laravel-pwa#229]
**Bagisto Version - V1.3.3**
**Description**
When trying to change the mobile number of the customer at the edit profile option there is no grid for mobile number. Hence unable to change the mobile number and edit the number.

**How to Reproduce**
**1.** Go to Edit Profile in PWA mobile view -> Mobile Number Grid is missing.
**2.** There should be the mobile number grid.

**Actual Result**
 Check out the video and screenshots for a better understanding of the concern.
 
 **Video**

https://user-images.githubusercontent.com/92721837/147728303-71a3fed3-8fc1-459a-9034-418252833247.mp4

**Expected Result**
Please add the mobile number grid to the profile edit. Please Fix the issue regarding this concern.

**Comment by naresh-webkul** [comment]
Invalid as it is already added in the addresses
https://prnt.sc/14q0F7_fA7AR
