### ISSUE TITLE
UI Issue in the Dashboard page at the  PWA mobile view 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#230]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA 
2. Go to Dashboard -> UI  issue.

**Image:**
![pwa](https://user-images.githubusercontent.com/92033944/154036777-0f7e4ad0-cc36-45c6-8a1c-fb9a41a7d04f.png)

**Comment by naresh-webkul** [comment]
not an issue:
https://prnt.sc/E2E7PKaZKoKO
