### ISSUE TITLE
Share button is not working in the product page at the PWA mobile view 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#231]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA.
2. Go to the product page  -> open product page -> Share button is not working.

**Image:**
![pwa1](https://user-images.githubusercontent.com/92033944/154040615-df3890f1-25a4-4123-8530-591efa53e6e0.png)

**Video:**

https://user-images.githubusercontent.com/92033944/154040687-dca77885-5f63-4faa-bbc8-70000eecbc58.mp4

**Expected Result:**
The share button should be working properly.

**Comment by naresh-webkul** [comment]
Invalid as it is already added in the addresses
https://prnt.sc/14q0F7_fA7AR

**Comment by naresh-webkul** [comment]
@Nikitajoshi39 
Make sure you have enable the web share API to use this feature.
