### ISSUE TITLE
UI  issue in between place order and amount to be paid at the PWA mobile view 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#232]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA.
2. Go to the product page  -> add to cart product  -> place the order.

**Actual Result:**
![pwa2](https://user-images.githubusercontent.com/92033944/154046729-e0ea4595-d081-44ac-9611-3c1d51342329.png)

https://user-images.githubusercontent.com/92033944/154061425-6a2a788d-a130-4154-95af-5dd9a8512ceb.mp4

**Expected Result:**
 Place order and amount to be paid should be managed equally.
![pwa3](https://user-images.githubusercontent.com/92033944/154047050-411e50e1-315c-48c1-ab71-2cea27dc3456.png)

**Comment by naresh-webkul** [comment]
invalid issue
