### ISSUE TITLE
When a customer add a review to the product,  add image option is not available.

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#233]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA.
2. Go to the product page  -> add your review  -> add image option is not available..

**Actual Result:**
![pwa4](https://user-images.githubusercontent.com/92033944/154059094-536c849b-db20-45c9-bef5-d77745736ce9.png)

**Expected result:**
 Add image option should be available.

**Comment by naresh-webkul** [comment]
feature added for product reviews

**Comment by Nikitajoshi39** [comment]
**fixed**
