### ISSUE TITLE
Vat id row  should be available on the add address page .

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#235]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA.
2. Go to the accounts  -> address book-> add a new address->vat id  enhancement.

**Image:**
UI issue in the country column.
![pwa6](https://user-images.githubusercontent.com/92033944/154066114-e468598c-420a-4e9a-bda7-68e9084fd523.png)

**Comment by naresh-webkul** [comment]
this is invalid issue
