### ISSUE TITLE
Arrow button should be working properly at the PWA mobile view

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#237]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA.
2. Go to the dashboard   -> recent orders->  downloadable orders -> arrow button is not working .

** Actual Image:**
![pwa8](https://user-images.githubusercontent.com/92033944/154211370-0be1d6ba-632d-45da-aa11-390b48e02eec.png)

**video:**

https://user-images.githubusercontent.com/92033944/154211235-32128dd1-ea8a-4f71-8520-6f75033f4433.mp4

**Expected result:**
]Arrow button should be working properly at the PWA mobile view

**Comment by naresh-webkul** [comment]
already added detail button at the bottom
