### ISSUE TITLE
Add to cart button option should be highlighted at the PWA mobile view 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#238]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA.
2. Go to the product page   -> add to cart button.

**Image:**

![pwa9](https://user-images.githubusercontent.com/92033944/154219216-bde9c71a-989d-46f2-8070-ab85be89a931.png)

**Comment by naresh-webkul** [comment]
no need to add this is default ui theme
