### ISSUE TITLE
Add to cart option should be available in the compare.

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#239]
**Bagisto Version - V1.3.3**

**Steps to Reproduce--**
1. Login in PWA.
2. Go to the accounts   -> compare.

**Image:**
![pwa10](https://user-images.githubusercontent.com/92033944/154222290-f80dcc2d-c84d-4550-b853-b55ac4638ca9.png)

**Comment by naresh-webkul** [comment]
Added a link to product detail page in compare section.
