### ISSUE TITLE
Pwa status  should be working properly at the admin end 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#248]
**Bagisto:v1.4.3**

**Laravel-PWA:v1.3.3**

**Description**
When the Pwa status is off in the admin end, It is showing in the sidebar.

**How to reproduce**
1. Go to the admin panel.
2. Select dashboard -> It is showing in the sidebar.

**Actual result:** 
It is showing in the sidebar.

![pwa](https://user-images.githubusercontent.com/92033944/168579726-76e1f248-3b6f-43bd-b2fb-ae16c073441f.png)

https://user-images.githubusercontent.com/92033944/168579863-1d85c784-7a61-47ac-82c6-956bf55231d4.mp4

**Excepted result**: The status of Pwa should be working.

**Comment by nikita-webkul** [comment]
fixed
