### ISSUE TITLE
Ui issue in the search page  at the pwa end 

### ISSUE THREAD

**Issue by Nikitajoshi39** [bagisto/laravel-pwa#249]
**Bagisto:v1.4.3**

**Laravel-PWA:v1.3.3**

**Description**
There is no space  in between recent search and clear all in the search page  .

**How to reproduce**
1. Go to the PWA end .
2. Select  search bar  -> search products .

**Actual result:** 
There is no space .

![pwa2](https://user-images.githubusercontent.com/92033944/168587966-59d6ac95-386c-478f-83ce-98b1b9f76307.png)

**Excepted result**: There should be some space between recent search and clear all data .

**Comment by nikita-webkul** [comment]
fixed
