### ISSUE TITLE
Order id is not showing  as per order setting in PWA

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-pwa#30]
order id is not coming according to configuration of order setting in pwa only

**Comment by bhanu-webkul** [comment]
expected oder id to display- https://prnt.sc/vl8ack
actual- https://prnt.sc/vl89z6

**Comment by bhanu-webkul** [comment]
not working properly yet, prefix suffix is not showing on order detail page ,order id is not showing properly on order success page

**Comment by shubhwebkul** [comment]
![Uploading Screenshot from 2020-11-19 22-44-22.png…]()

**Comment by shubhwebkul** [comment]
![Screenshot from 2020-11-19 22-44-22](https://user-images.githubusercontent.com/41280839/99700261-f18f9500-2ab8-11eb-8e90-17a1b8fa4017.png)

**Comment by shubhwebkul** [comment]
![Screenshot from 2020-11-19 22-48-36](https://user-images.githubusercontent.com/41280839/99700614-6531a200-2ab9-11eb-8676-1bf9c936a550.png)

**Comment by jyoti-webkul** [comment]
When click on to view order details prefix added for order is not showing.

--------------------------------------

![Workspace 1_124](https://user-images.githubusercontent.com/45203177/100369689-3ec8b500-302b-11eb-9aa7-ac6e3f4a9ea8.png)

![Uploading Workspace 1_125.png…]()

**Comment by jyoti-webkul** [comment]
- Fixed

----------------------

![Workspace 1_145](https://user-images.githubusercontent.com/45203177/100704409-805eb480-33cb-11eb-80dd-6aebf2ac1a62.png)
