### ISSUE TITLE
in place of date its coming invalid date under submitted on in PWA

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-pwa#42]
https://prnt.sc/t2t3jl

**Comment by bhanu-webkul** [comment]
still invalid date showing on opening review

![Screenshot 2020-06-23 10:00:32](https://user-images.githubusercontent.com/52821836/85361097-9cb31700-b538-11ea-81cf-ab933c8c4b53.png)

**Comment by prateek-webkul** [comment]
Fixed

**Comment by bhanu-webkul** [comment]
Done
