### ISSUE TITLE
Field  name is showing inside field while customer sign up in ar

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-pwa#43]
![Screenshot 2020-06-20 10:37:00](https://user-images.githubusercontent.com/52821836/85192934-42b91400-b2e2-11ea-9e9e-e6d50f560dff.png)

**Comment by bhanu-webkul** [comment]
same at forgot password page

https://prnt.sc/t35hng

**Comment by prateek-webkul** [comment]
@bhanu-webkul, not an issue works as same in en locale also
