### ISSUE TITLE
Apply coupon doesn't work

### ISSUE THREAD

**Issue by musabibnusiraj** [bagisto/laravel-pwa#47]
When clicking the Applied coupon button then below error occurs.

![image](https://user-images.githubusercontent.com/47845204/85367215-78f6cd80-b546-11ea-802c-e947b1d3649d.png)

![image](https://user-images.githubusercontent.com/47845204/85367324-a93e6c00-b546-11ea-9a11-a6ca99d0dddd.png)

**Comment by bhanu-webkul** [comment]
@musabibnusiraj 

This issues has been fixed now.
![Screenshot 2020-06-23 19:27:19](https://user-images.githubusercontent.com/52821836/85413074-f5f66700-b587-11ea-9a29-2f6b72e356e9.png)

**Comment by musabibnusiraj** [comment]
from master branch?

**Comment by bhanu-webkul** [comment]
@musabibnusiraj 
Issue has been fixed but not merged in master yet as we are working on other issues of pwa, will merge in master tomorrow onward.

**Comment by musabibnusiraj** [comment]
Ok, Thanks.
