### ISSUE TITLE
getting error on opening pwa on safari broswer 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-pwa#49]
![Screenshot 2020-06-26 16:40:37](https://user-images.githubusercontent.com/52821836/85851468-5e358a80-b7cc-11ea-9a9d-c1b7a31ca721.png)

**Comment by jyoti-webkul** [comment]
- Fixed

------------------

![Workspace 1_148](https://user-images.githubusercontent.com/45203177/100738643-e400d600-33fb-11eb-89a8-767fe8cc2355.png)
