### ISSUE TITLE
error composer install --no-dev

### ISSUE THREAD

**Issue by marcelowu** [bagisto/laravel-pwa#68]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Barryvdh\Debugbar\ServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by shubhwebkul** [comment]
Hello there,

Can you please mention steps to reproduce or share screenshot of this error because we are not facing such type of exception.
