### ISSUE TITLE
Getting error while checking checking invoice detail at customer end 

### ISSUE THREAD

**Issue by bhanu-webkul** [bagisto/laravel-pwa#85]
![Screenshot from 2020-11-04 12-13-40](https://user-images.githubusercontent.com/52821836/98078088-68147c00-1e97-11eb-95f2-d789109daec3.png)

**Comment by bhanu-webkul** [comment]
still getting error 
![Screenshot from 2020-11-16 18-34-05](https://user-images.githubusercontent.com/52821836/99256154-f9da9c80-283a-11eb-9dd9-dd3de6d4bce7.png)

**Comment by bhanu-webkul** [comment]
no error found but there is no response on clicking on view invoice or save invoice

**Comment by jyoti-webkul** [comment]
Getting blank page when click on View invoice.

-------------------------------------------

![download (22)](https://user-images.githubusercontent.com/45203177/100371803-55244000-302e-11eb-848a-a9c4665c3738.png)
![Workspace 1_127](https://user-images.githubusercontent.com/45203177/100371817-5b1a2100-302e-11eb-9360-3ee610f0934a.png)

**Comment by shubhwebkul** [comment]
issue raised #126
